name : Cypress Smoke test run on Chrome
on: push
jobs : 
     cypress_run_chrome:
       runs-on: ubuntu-24.04 
       steps:
          - name: Checkout The Code
            uses: actions/checkout@v4
     
          - name: Cypress run
            uses: cypress-io/github-action@v6
            with:
                command: npm run smoke-test